include:
- ../../../containers/compose.yml

services:
  target:
    image: ${UCB_CONTAINER_REGISTRY}delulu:1.0.1
    init: true
    #build:
      #context: ./victim

# Is this used?
networks:
  no-internet:
    driver: bridge
    internal: true
