include:
- ../../../containers/compose.yml
services:
  target:
    #build:
      #context: ./target
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      interval: 1s
      retries: 30
      test:
      - CMD
      - curl
      - -f
      - http://target:9091/health
      timeout: 20s
    image: ${UCB_CONTAINER_REGISTRY}cve-2024-34359/target:1.0.4
    restart: unless-stopped
