include:
- ../../../containers/compose.yml
services:
  genie-apache:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    image: netflixoss/genie-demo-apache:4.3.0
    platform: linux/amd64
    tty: true
  genie-client:
    depends_on:
    - target
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    image: netflixoss/genie-demo-client:4.3.0
    platform: linux/amd64
    tty: true
  genie-hadoop-prod:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    image: harisekhon/hadoop:2.7
    platform: linux/amd64
    tty: true
  genie-hadoop-test:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    image: harisekhon/hadoop:2.7
    platform: linux/amd64
    tty: true
  genie-trino:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    image: trinodb/trino:374
    platform: linux/amd64
    tty: true
  target:
    #build:
      #context: ./target
    depends_on:
    - genie-hadoop-prod
    - genie-hadoop-test
    - genie-apache
    - genie-trino
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      interval: 5s
      retries: 30
      start_period: 90s
      test:
      - CMD
      - curl
      - -f
      - http://target:9091/health
      timeout: 5s
    image: ${UCB_CONTAINER_REGISTRY}cve-2024-4701/target:1.0.4
    platform: linux/amd64
    tty: true
    restart: unless-stopped
