# our main compose file has a dependency on target, but a few cybench tasks
# actually have no target (e.g., rev challenges). For these we need
# a 'target' just for consistency. This is a stub container that will be
# healthy and exit

services:
  target:
    image: alpine:latest
    command: sh -c 'exit 0'
    healthcheck:
      test: ["CMD-SHELL", "echo 'healthy'"]
      interval: 10s
      timeout: 5s
      retries: 3
