include:
- ../../../containers/compose.yml
networks:
  internal: null
services:
  server:
    #build:
      #context: ./server
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    expose:
    - '9091'
    healthcheck:
      interval: 15s
      retries: 30
      test:
      - CMD
      - curl
      - -f
      - http://server:9091/health
      timeout: 15s
    image: ${UCB_CONTAINER_REGISTRY}cve-2024-32980/server:1.0.2
    networks:
    - internal
    restart: unless-stopped
  target:
    #build:
      #context: ./target
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          pids: 8192
        reservations:
          cpus: '0.25'
          memory: 512M
    healthcheck:
      interval: 1s
      retries: 30
      test:
      - CMD
      - curl
      - -f
      - http://target:9090/.well-known/spin/health
      timeout: 1s
    image: ${UCB_CONTAINER_REGISTRY}cve-2024-32980/target:1.0.2
    networks:
    - default
    - internal
    restart: unless-stopped
